extends Node
## Global beat clock. Generates its own music procedurally; SFX are Kenney CC0 .ogg files,
## and exposes song_time / beat signal / timing-offset helpers for rhythm judging.

signal beat(n: int)
signal step(n: int)  # 16th-note grid

const MIX_RATE := 22050
const LOOP_BEATS := 8
## Original 4-on-the-floor tracks generated by tools/gen_music.py (sample-exact loops: sample 0 =
## beat 0, `beats` = loop length). role: menu / battle / boss. hits = off-beat 16th steps (0..15 per
## bar) where the lead plays - bosses fire shots on them.
const TRACKS := [
	{"name": "Starlight", "path": "res://assets/music/starlight.ogg", "bpm": 105.0, "beats": 64, "offset": 0.0, "hits": [], "role": "menu"},
	{"name": "Neon Drive", "path": "res://assets/music/neon_drive.ogg", "bpm": 126.0, "beats": 64, "offset": 0.0, "hits": [3, 6, 10, 14], "role": "battle"},
	{"name": "Pixel Rave", "path": "res://assets/music/pixel_rave.ogg", "bpm": 135.0, "beats": 64, "offset": 0.0, "hits": [3, 6, 11, 14], "role": "battle"},
	{"name": "Sub Zero", "path": "res://assets/music/sub_zero.ogg", "bpm": 120.0, "beats": 64, "offset": 0.0, "hits": [2, 6, 10, 14], "role": "battle"},
	{"name": "Maestro Rush", "path": "res://assets/music/maestro_rush.ogg", "bpm": 140.0, "beats": 64, "offset": 0.0, "hits": [3, 7, 11, 14], "role": "boss"},
]
const CLAP_TYPES := ["clap", "rim", "wood", "snap"]
const CLAP_NAMES := ["ハンドクラップ", "リムショット", "ウッドブロック", "フィンガースナップ"]

var track_idx := 0
var bpm := 120.0
var track_offset := 0.0
var hits: Array = []  # off-beat 16th steps (0..15 per bar) where the music accents; measured per track
var _last_step := -1
var guide := false  # beat-guide claps active (battle / tutorial / settings / calibration)
var force_clap := false  # countdown claps ignore the on/off option
var _last_clap_beat := -1
var _clap: AudioStreamPlayer
var _clap_streams: Array = []
var _lat := 0.0
var _last_battle_idx := -1
var spb: float = 0.5
var song_time: float = 0.0
var running: bool = false
var clock_only: bool = false  # headless / tests: ignore audio position

var _music: AudioStreamPlayer
var _sfx: Dictionary = {}
var _loop_len: float
var _loops: int = 0
var _last_pos: float = 0.0
var _last_beat: int = -1
var _manual_loop := false

func _ready() -> void:
	clock_only = DisplayServer.get_name() == "headless"
	_music = AudioStreamPlayer.new()
	_music.playback_type = AudioServer.PLAYBACK_TYPE_STREAM
	_apply_track(role_index("menu"))
	_music.volume_db = -6.0
	_music.bus = "Music"
	add_child(_music)
	var d := "res://assets/kenney_interface_sounds/"
	_sfx["perfect"] = load(d + "confirmation_002.ogg")
	_sfx["good"] = load(d + "click_003.ogg")
	_sfx["miss"] = load(d + "error_003.ogg")
	_sfx["hit"] = load(d + "drop_001.ogg")
	_sfx["boom"] = load(d + "bong_001.ogg")
	_sfx["card"] = load(d + "pluck_001.ogg")
	_sfx["select"] = load(d + "select_002.ogg")
	_sfx["tick"] = load(d + "tick_002.ogg")
	_sfx["toggle"] = load(d + "toggle_001.ogg")
	_sfx["big"] = load(d + "maximize_006.ogg")
	_sfx["open"] = load(d + "open_001.ogg")
	_sfx["win"] = load(d + "confirmation_004.ogg")
	for ct in CLAP_TYPES:
		_clap_streams.append(load("res://assets/sfx/clap_%s.wav" % ct))
	_clap = AudioStreamPlayer.new()
	_clap.playback_type = AudioServer.PLAYBACK_TYPE_STREAM
	_clap.bus = "SFX"
	add_child(_clap)
	for k in _sfx:
		var p := AudioStreamPlayer.new()
		p.playback_type = AudioServer.PLAYBACK_TYPE_STREAM
		p.stream = _sfx[k]
		p.volume_db = -6.0
		p.bus = "SFX"
		add_child(p)
		_sfx[k] = p

func _apply_track(i: int) -> void:
	track_idx = i
	var t: Dictionary = TRACKS[i]
	bpm = t["bpm"]
	spb = 60.0 / bpm
	track_offset = t["offset"]
	hits = t.get("hits", [])
	if ResourceLoader.exists(t["path"]):
		var st: AudioStream = load(t["path"])
		if st is AudioStreamOggVorbis:
			(st as AudioStreamOggVorbis).loop = true  # sample-exact loop -> seamless
		_music.stream = st
		_loop_len = spb * int(t["beats"])
		_manual_loop = false
	else:
		bpm = 120.0
		spb = 0.5
		track_offset = 0.0
		_music.stream = _make_music()
		_loop_len = spb * LOOP_BEATS
		_manual_loop = false

func _reset_clock() -> void:
	song_time = 0.0
	_loops = 0
	_last_pos = 0.0
	_last_beat = -1
	_last_step = -1
	_last_clap_beat = -1

func start() -> void:
	_reset_clock()
	running = true
	if not clock_only:
		_music.play()

## Switch to another track and restart it from the top (restarts the beat clock).
func set_track(i: int) -> void:
	i = clampi(i, 0, TRACKS.size() - 1)
	var was_playing := running and not clock_only
	_music.stop()
	_apply_track(i)
	_reset_clock()
	if was_playing:
		_music.play()

func role_index(role: String) -> int:
	for i in TRACKS.size():
		if TRACKS[i]["role"] == role:
			return i
	return 0

## TRACKS indices usable as battle BGM (shown in the settings selector).
func battle_tracks() -> Array:
	var out: Array = []
	for i in TRACKS.size():
		if TRACKS[i]["role"] == "battle":
			out.append(i)
	return out

## Menu / map / shop music: only switch when we're not already on the menu track.
func play_menu() -> void:
	var mi := role_index("menu")
	if track_idx != mi:
		set_track(mi)

## Start a fresh BGM for a battle (always restarts from beat 0).
## mode: index into battle_tracks() or -1 for random; `boss` forces the boss track.
func start_battle_track(mode: int, boss: bool) -> void:
	if boss:
		set_track(role_index("boss"))
		return
	var bt := battle_tracks()
	var pick: int
	if mode >= 0 and mode < bt.size():
		pick = bt[mode]
	else:
		var opts: Array = []
		for i in bt:
			if i != _last_battle_idx:
				opts.append(i)
		pick = opts.pick_random() if not opts.is_empty() else bt[0]
	_last_battle_idx = pick
	set_track(pick)

func preview_clap() -> void:
	_play_clap()

func _play_clap() -> void:
	if clock_only:
		return
	_clap.stream = _clap_streams[clampi(Settings.clap_type, 0, _clap_streams.size() - 1)]
	_clap.volume_db = linear_to_db(maxf(Settings.clap_vol, 0.0001)) + 2.0
	_clap.play()

func play_sfx(kind: String, pitch := 1.0) -> void:
	if clock_only or not _sfx.has(kind):
		return
	var p := _sfx[kind] as AudioStreamPlayer
	p.pitch_scale = pitch
	p.play()

## Low-pass the music (used when HP is critical).
func set_muffle(on: bool) -> void:
	var bi := AudioServer.get_bus_index("Music")
	if AudioServer.get_bus_effect_count(bi) > 0:
		AudioServer.set_bus_effect_enabled(bi, 0, on)

var offset: float:
	get:
		return Settings.offset_ms / 1000.0 + track_offset

func set_paused(p: bool) -> void:
	running = not p
	_music.stream_paused = p

## Offset ignoring the user setting (used by the calibration screen).
func raw_beat_offset() -> float:
	var phase := fposmod(song_time - track_offset, spb)
	return phase if phase < spb * 0.5 else phase - spb

func _process(delta: float) -> void:
	if not running:
		return
	if clock_only or not _music.playing:
		song_time += delta
	else:
		var p := _music.get_playback_position() + AudioServer.get_time_since_last_mix()
		if p < _last_pos - 1.0:
			_loops += 1
		_last_pos = p
		_lat = AudioServer.get_output_latency()
		song_time = _loops * _loop_len + p - _lat
	var cur := floori((song_time - offset) / spb)
	while _last_beat < cur:
		_last_beat += 1
		beat.emit(_last_beat)
	var cs := floori((song_time - offset) / (spb / 4.0))
	while _last_step < cs:
		_last_step += 1
		step.emit(_last_step)
	# Guide claps are triggered `latency` early so they reach the speakers together with the music's beat.
	var cb := floori((song_time + _lat - track_offset) / spb)
	while _last_clap_beat < cb:
		_last_clap_beat += 1
		if force_clap or (guide and Settings.clap_on):
			if force_clap or Settings.clap_pat == 0 or (_last_clap_beat % 4) in [1, 3]:
				_play_clap()

## Seconds from the nearest beat; positive = late, negative = early.
func beat_offset() -> float:
	var phase := fposmod(song_time - offset, spb)
	return phase if phase < spb * 0.5 else phase - spb

## 0..1 within the current beat (0 = on the beat).
func beat_phase() -> float:
	return fposmod(song_time - offset, spb) / spb

# ---- procedural audio ------------------------------------------------------

func _make_music() -> AudioStreamWAV:
	var n := int(MIX_RATE * spb * LOOP_BEATS)
	var data := PackedByteArray()
	data.resize(n * 2)
	var bass := [55.0, 55.0, 65.41, 49.0]
	var lead := [220.0, 261.63, 329.63, 261.63, 196.0, 246.94, 293.66, 246.94]
	for i in n:
		var t := float(i) / MIX_RATE
		var bt := fposmod(t, spb)
		var s := 0.0
		# kick on every beat
		var phase := 45.0 * bt + 90.0 * (1.0 - exp(-30.0 * bt)) / 30.0
		s += 0.7 * sin(TAU * phase) * exp(-bt * 12.0)
		# off-beat hat
		var ht := fposmod(t - spb * 0.5, spb)
		s += 0.10 * (randf() * 2.0 - 1.0) * exp(-ht * 70.0)
		# bass with pseudo side-chain
		var bn: float = bass[(int(t / spb) / 2) % 4]
		s += 0.22 * sin(TAU * bn * t) * minf(1.0, bt * 8.0)
		# eighth-note lead
		var ei := int(t / (spb * 0.5))
		var et := fposmod(t, spb * 0.5)
		var lf: float = lead[ei % 8]
		s += 0.07 * signf(sin(TAU * lf * et)) * exp(-et * 9.0)
		data.encode_s16(i * 2, int(clampf(s * 0.8, -1.0, 1.0) * 30000.0))
	return _wav(data, true)

func _wav(data: PackedByteArray, looped: bool) -> AudioStreamWAV:
	var w := AudioStreamWAV.new()
	w.format = AudioStreamWAV.FORMAT_16_BITS
	w.mix_rate = MIX_RATE
	w.stereo = false
	w.data = data
	if looped:
		w.loop_mode = AudioStreamWAV.LOOP_FORWARD
		w.loop_begin = 0
		w.loop_end = data.size() / 2
	return w
