class_name Loc
## Minimal i18n: source strings are Japanese; Loc.t() maps them to English when Settings.lang == "en".
## Templates with %d / {param} placeholders are translated BEFORE formatting (see Cards.def, Loc.t(...) % args).

static var _cache := {}

static func clear_cache() -> void:
	_cache.clear()

static var _phr: Array = []
static var _ja_re: RegEx
static var _fmt_re: RegEx = RegEx.create_from_string("%[-+ 0-9.]*[dsfi]")

## Japanese -> English when Settings.lang == "en". Exact match first, then phrase substitution
## (handles composites like "BOSS: " + name), cached per input string.
static func t(s: String) -> String:
	if Settings.lang != "en" or s.is_empty():
		return s
	if EN.has(s):
		return EN[s]
	if _cache.has(s):
		return _cache[s]
	if _ja_re == null:
		_ja_re = RegEx.create_from_string("[\u3040-\u30ff\u4e00-\u9fff]")
	var out := s
	if _ja_re.search(s) != null:
		if _phr.is_empty():
			for k in EN.keys():
				if String(k).length() >= 2 and not _fmt_re.search(k) and not ("{" in k):
					_phr.append(k)
			_phr.sort_custom(func(a: String, b: String) -> bool: return a.length() > b.length())
		for k in _phr:
			if k in out:
				out = out.replace(k, EN[k])
	if _cache.size() > 3000:
		_cache.clear()
	_cache[s] = out
	return out

const EN := {
	"  (クリアで次の段階が解放)": "  (clear to unlock the next level)",
	"  残り%.0f": "  %.0fs left",
	" 早すぎ": " too early",
	" 早め": " early",
	" 遅すぎ": " too late",
	" 遅め": " late",
	"%d / %d階": "Floor %d / %d",
	"%s%s   撃破 %d   %dG": "%s%s   Kills %d   %dG",
	"(なし)": "(none)",
	"(スマホは横向き+全画面がおすすめ)": "(Phones: landscape + fullscreen recommended)",
	"+ エリートの出現率UP。": "+ Elites appear more often.",
	"+ ボスのHP+25%。": "+ Boss HP +25%.",
	"+ 敵の移動速度+4% / 獲得ゴールド-15%。": "+ Enemy speed +4% / Gold gain -15%.",
	"+ 最大HP-15%。": "+ Max HP -15%.",
	"+%d G 獲得  /  カードを1枚選ぼう": "+%d G  /  Pick a card",
	"10ビート与ダメージ2倍+フィーバーゲージ+3。": "Double damage for 10 beats + Fever gauge +3.",
	"10拍ごとに小さなノヴァが自動発動。": "Every 10 beats, a small Nova triggers automatically.",
	"10階層のマップを進み、最上階のボスを倒せ。\nバトル・エリート・休憩・ショップ・イベント・宝箱。\n難易度(アセンション)で何度も挑める。": "Climb a 10-floor map and defeat the boss.\nBattles, elites, rests, shops, events, treasure.\nReplay at higher Ascension levels.",
	"15%の確率でカードのコストが0になる。": "15% chance a card costs 0.",
	"1ランの最多撃破: %d": "Most kills in a run: %d",
	"2拍ごとにシールド+1(10まで)。": "+1 shield every 2 beats (up to 10).",
	"2拍後に着弾 {dmg}": "Lands in 2 beats: {dmg}",
	"30Gでカードを1枚買う": "Buy a card for 30G",
	"3種類のボスすべてを倒す。": "Defeat all 3 kinds of boss.",
	"4拍ごとシールド+{n}": "+{n} shield every 4 beats",
	"8ビートの間、敵を大きく減速。": "Greatly slow enemies for 8 beats.",
	"8体撃破ごとにHP1回復。": "Heal 1 HP every 8 kills.",
	"BOSS戦": "BOSS",
	"CC0素材: Kenney / Joth": "CC0 assets: Kenney / Joth",
	"HP %d   速度 %d%%   クリア%d回": "HP %d   Speed %d%%   Clears %d",
	"HPを{n}回復。": "Heal {n} HP.",
	"NEW! はじめての方はここから": "NEW! Start here if you're new",
	"PERFECT判定の幅+25ms。コンボ1あたりのダメージ上昇+1%。": "PERFECT window +25ms. +1% more damage per combo.",
	"PERFECT判定の幅が+20ms広がる。": "PERFECT window +20ms.",
	"PERFECT累計: %d": "Total PERFECTs: %d",
	"{beats}ビートの間、与ダメージ2倍。": "Double damage for {beats} beats.",
	"{beats}ビートの間、剣{n}本が周囲を回る。": "{n} blades orbit you for {beats} beats.",
	"{beats}ビートの間、敵を大きく減速。": "Greatly slow enemies for {beats} beats.",
	"{k}体撃破でHP+1": "+1 HP per {k} kills",
	"{k}拍ごとHP+1": "+1 HP every {k} beats",
	"{n}体に雷撃 各{dmg}": "Lightning x{n}: {dmg} each",
	"♪ 音が出ます": "♪ Sound on",
	"「%s」が強化された。HPが10減った。": "\"%s\" was upgraded. Lost 10 HP.",
	"「%s」を手に入れた。": "Got \"%s\".",
	"「いい曲(カード)があるよ。持ち札を整理するのもアリさ」": "\"Got some good tunes (cards). I can also help you thin your deck.\"",
	"【パワー】4ビートごとにシールド{n}。": "[Power] +{n} shield every 4 beats.",
	"【パワー】{k}体撃破ごとにHP1回復。": "[Power] Heal 1 HP every {k} kills.",
	"【パワー】{k}拍ごとにHP1回復。": "[Power] Heal 1 HP every {k} beats.",
	"【パワー】自動弾のダメージ+{n}。": "[Power] Auto-bolt damage +{n}.",
	"【パワー】触れた敵に{n}ダメージ。": "[Power] {n} damage to enemies that touch you.",
	"あきらめる": "Give up",
	"あそびかた": "How to Play",
	"あなたは静かに立ち去った。": "You quietly walked away.",
	"ここ！": "Here!",
	"さすらいの吟遊詩人": "Wandering Bard",
	"すべてのキャラでクリアする。": "Clear the game with every character.",
	"はじめる": "Start",
	"まずは移動してみよう。": "First, try moving.",
	"キー: WASD / 矢印   スマホ: 画面をドラッグ": "Keys: WASD / Arrows   Phone: drag on screen",
	"もう一度": "Retry",
	"もどる": "Back",
	"やめる": "Cancel",
	"やり直す": "Retry",
	"アセンション %d": "Ascension %d",
	"アセンション3以上でクリアする。": "Clear at Ascension 3 or higher.",
	"アタック": "Attack",
	"アルカナ +1": "Arcana +1",
	"アルカナ・リズム": "Arcane Rhythm",
	"イベント": "Event",
	"イージス": "Aegis",
	"イージス！": "Aegis!",
	"ウィザード": "Wizard",
	"ウェーブ %d": "Wave %d",
	"ウェーブが延々と続くサバイバル。\nカード報酬。\n10ウェーブごとにボスが出現！": "Endless survival waves.\nCard rewards.\nA boss every 10 waves!",
	"ウェーブが延々と続くサバイバル。\n勝ち抜くごとにカード報酬。\n10ウェーブごとにボスが出現！": "Endless survival waves.\nCard reward after each win.\nA boss every 10 waves!",
	"エコー": "Echo",
	"エコーの貝殻": "Echo Shell",
	"エコー待機": "Echo ready",
	"エネルギー(左上の黄色い丸)は1秒に1回復。": "Energy (yellow dots, top-left) recovers 1 per second.",
	"左下『次のカード』で次に引くカードが分かる。": "'Next card' (bottom-left) shows what you draw next.",
	"エネルギー+{n}": "Energy +{n}",
	"エネルギーを3得る。": "Gain 3 energy.",
	"エネルギーを{n}得る。": "Gain {n} energy.",
	"エネルギー不足": "Not enough energy",
	"エリート": "Elite",
	"エリート出現！": "ELITE!",
	"エンドレス": "Endless",
	"エンドレス ウェーブ%d": "Endless Wave %d",
	"エンドレス10": "Endless 10",
	"エンドレス20": "Endless 20",
	"エンドレスで10ウェーブに到達する。": "Reach wave 10 in Endless.",
	"エンドレスで20ウェーブに到達する。": "Reach wave 20 in Endless.",
	"エンドレス最高: %dウェーブ": "Endless best: wave %d",
	"オーバードライブ": "Overdrive",
	"オーバードライブ x%d": "Overdrive x%d",
	"オーラ %d/%d": "Aura %d/%d",
	"カード1枚を無料で削除": "Remove a card for free",
	"カードを1枚削除した。": "Removed a card.",
	"カードを1枚選んで削除する。": "Choose a card to remove.",
	"カードを使ってみよう。": "Now play a card.",
	"[1]〜[5]キー / タップ。上のレーンで『丸が輪に重なる瞬間』が拍だ！": "Keys [1]-[5] / tap. The beat is the moment a dot lands on the ring in the top lane!",
	"カードを削除 (%d G)": "Remove a card (%d G)",
	"カード商人": "Card Dealer",
	"ガード": "Guard",
	"キャラクター選択": "Choose Your Character",
	"キャリブレーション": "Calibration",
	"クリア %d回 / 最高 %d階": "Clears %d / Best floor %d",
	"クリア回数: %d": "Clears: %d",
	"コレクター": "Collector",
	"コンボ x%d": "Combo x%d",
	"コンボ1あたりのダメージ上昇が3%になる。": "Each combo adds +3% damage instead of +2%.",
	"コンボ×{k}のシールド": "Shield = combo x{k}",
	"コンボが5の倍数になるたび、エネルギー+1。": "+1 energy whenever the combo reaches a multiple of 5.",
	"コンボの達人": "Combo Master",
	"コンボを10にする。": "Reach a 10 combo.",
	"コンボを20にする。": "Reach a 20 combo.",
	"コンボガード": "Combo Guard",
	"コンボ数×{k}のシールドを得る(最大コンボ20)。": "Gain shield equal to combo x{k} (max combo 20).",
	"ゴールドが足りない。": "Not enough gold.",
	"サージ": "Surge",
	"ショップ": "Shop",
	"シールド %d": "Shield %d",
	"シールド+{n}": "Shield +{n}",
	"シールドを20得る。": "Gain 20 shield.",
	"シールドを{n}得る。": "Gain {n} shield.",
	"シールド発生器": "Shield Generator",
	"スキル": "Skill",
	"スコープ": "Scope",
	"ステージ攻略": "Climb",
	"ステージ攻略でボスを倒す。": "Defeat the boss in Climb mode.",
	"ステージ攻略を1回クリアで解放": "Unlock by clearing Climb mode once",
	"ソニックブーム": "Sonic Boom",
	"タップ / クリック / キーでスタート": "Tap / Click / Press any key",
	"ダメージ +%d%%": "Damage +%d%%",
	"ダメージを受けずにボスを倒す。": "Defeat a boss without taking damage.",
	"チェインボルト": "Chain Bolt",
	"チュートリアル": "Tutorial",
	"チュートリアルを完了する。": "Complete the tutorial.",
	"チュートリアル完了！": "Tutorial complete!",
	"デイリーラン": "Daily Run",
	"デイリーランをクリアする。": "Clear a Daily Run.",
	"デイリー挑戦": "Daily Challenger",
	"デッキ (%d)": "Deck (%d)",
	"デッキ (%d枚)": "Deck (%d cards)",
	"デッキ: %d枚    レリック: %d個    所持金: %dG": "Deck: %d    Relics: %d    Gold: %dG",
	"デッキを25枚以上にする。": "Have 25 or more cards in your deck.",
	"デッキ構築家": "Deck Builder",
	"トゲ %d": "Thorns %d",
	"トゲのオーラ": "Thorn Aura",
	"ドラマー": "Drummer",
	"ドラムスティック": "Drumstick",
	"ドラムメイジ": "Drum Mage",
	"ドラムロール": "Drum Roll",
	"ノリノリ": "In the Groove",
	"ノヴァ": "Nova",
	"ハートビート": "Heartbeat",
	"バトル": "Battle",
	"バトル開始": "BATTLE START",
	"パルスショット": "Pulse Shot",
	"パワー": "Power",
	"ヒール": "Heal",
	"ビート": "Beat",
	"ビートに乗って、デッキで生き残れ。": "Ride the beat. Survive with your deck.",
	"ビートブレード": "Beat Blades",
	"ビートリング": "Beat Ring",
	"フィーバー+{n}": "Fever +{n}",
	"フィーバーを発動させる。": "Trigger Fever.",
	"フィーバーゲージ+{n}。廃棄。": "Fever gauge +{n}. Exhaust.",
	"フィーバーゲージが8で満タンになる。": "Fever gauge fills at 8.",
	"フィーバーブースト": "Fever Boost",
	"フィーバー発動: %d回": "Fevers triggered: %d",
	"フィーバー終了": "Fever over",
	"フィーバー！": "Fever!",
	"フェイズステップ": "Phase Step",
	"フォートレス": "Fortress",
	"フォートレス +%d": "Fortress +%d",
	"フリーズビート": "Freeze Beat",
	"フルスクリーン": "Fullscreen",
	"フレンジー": "Frenzy",
	"フレンジー %d": "Frenzy %d",
	"ブレード %d": "Blades %d",
	"ブーストアンプ": "Boost Amp",
	"プレイ %d回   クリア %d回   最高到達 %d階   エンドレス最高 %dウェーブ   最多撃破 %d": "Runs %d   Clears %d   Best floor %d   Endless best wave %d   Most kills %d",
	"プレイ回数: %d": "Runs played: %d",
	"ヘッドホン": "Headphones",
	"ヘビーコード": "Heavy Chord",
	"ベースデーモン": "Bass Demon",
	"ベースドロップ": "Bass Drop",
	"ボス": "Boss",
	"ボスハンター": "Boss Hunter",
	"ポーション: %s - %s": "Potion: %s - %s",
	"ポーションを使う。": "Use a potion.",
	"ポーションを持てる数+1。": "+1 potion slot.",
	"ポーションベルト": "Potion Belt",
	"ポーズ": "PAUSED",
	"マウスホイール / ドラッグ / ▲▼でスクロール (%d/%d)": "Scroll with wheel / drag / ▲▼ (%d/%d)",
	"メテオコール": "Meteor Call",
	"メトロノーム": "Metronome",
	"メトロノーム・ジャイアント": "Metronome Giant",
	"メニューへ": "Menu",
	"モード選択": "Select Mode",
	"ヤジを飛ばす: 30G獲得 / HP-8": "Heckle: gain 30G / lose 8 HP",
	"ラッキー！": "Lucky!",
	"ランダム (戦闘ごと)": "Random (per battle)",
	"リズムの基礎": "Rhythm Basics",
	"リズムマスター": "Rhythm Master",
	"リプレイ": "Replay",
	"リーチウェーブ": "Leech Wave",
	"レゾナンス": "Resonance",
	"レゾナンス +%d": "Resonance +%d",
	"レリック: %s - %s": "Relic: %s - %s",
	"レリックを8個持つ。": "Hold 8 relics.",
	"レンジャー": "Ranger",
	"ロック中": "Locked",
	"ヴァイキング": "Viking",
	"不気味に唸るアンプ。触れると力が湧いてきそうだ。": "An amp humming eerily. Touching it might grant power.",
	"与ダメ2倍 {beats}拍": "2x damage, {beats} beats",
	"中は空っぽだった…": "It was empty...",
	"予備電池": "Spare Battery",
	"今日だけの固定マップ・キャラ・特殊ルール。\n本日のルール:\n": "Fixed map, character and a special rule, today only.\nToday's rule:\n",
	"今日の記録: %d階": "Today's best: floor %d",
	"今日は未挑戦": "Not played today",
	"仕上げ！ 敵を10体倒そう。": "Finish up! Defeat 10 enemies.",
	"(チュートリアル中は倒れません)": "(You can't lose during the tutorial)",
	"休": "R",
	"休む  HP +%d": "Rest  HP +%d",
	"休憩所": "Rest Site",
	"休憩所の回復量が45%になる。": "Resting heals 45% instead of 30%.",
	"低音の祭壇": "Bass Altar",
	"何も起こらなかった。": "Nothing happened.",
	"俊足のブーツ": "Swift Boots",
	"全ての敵に40ダメージ。": "40 damage to all enemies.",
	"全ての敵に{dmg}ダメージ。廃棄。": "{dmg} damage to ALL enemies. Exhaust.",
	"全カード強化済みでスタート": "Start with every card upgraded",
	"全体に{dmg}": "All enemies: {dmg}",
	"全員集合": "All Together",
	"全方位に{n}発 各{dmg}": "{n} shots in all directions: {dmg} each",
	"全方位に弾を{n}発。各{dmg}ダメージ。": "Fire {n} bolts in all directions. {dmg} damage each.",
	"円が光るビートに合わせて SPACE かクリックを10回。": "Press SPACE or click 10 times with the flashing beat.",
	"再開": "Resume",
	"出発！": "GO!",
	"初めての方は、メニューの『あそびかた』でリズムの基本を練習できます": "New? Practice the rhythm basics with 'How to Play' in the menu.",
	"初クリア": "First Clear",
	"初期デッキ": "Starting deck",
	"判定オフセット": "Timing offset",
	"到達ウェーブ: %d": "Wave reached: %d",
	"到達階層: %d / %d": "Floor reached: %d / %d",
	"削除するカードを選ぶ (%dG)": "Choose a card to remove (%dG)",
	"削除するカードを選ぶ (無料)": "Choose a card to remove (free)",
	"前方の扇形に{dmg}ダメージ+吹き飛ばし+2拍スタン。": "{dmg} damage in a forward cone + knockback + 2-beat stun.",
	"前方を貫く極太ビーム。{dmg}ダメージ。": "A huge piercing beam forward. {dmg} damage.",
	"剣{n}本 {beats}拍": "{n} blades, {beats} beats",
	"力": "E",
	"効果音量": "SFX volume",
	"勝利！": "VICTORY!",
	"千体撃破": "Thousand Slayer",
	"受け取る": "Take",
	"吸血の牙": "Vampire Fang",
	"吸血オーラ": "Vampire Aura",
	"周囲に{dmg}ダメージ+吹き飛ばし。": "{dmg} damage around you + knockback.",
	"周囲に{dmg}ダメージ。命中ごとにHP1回復(最大{max})。": "{dmg} damage around you. Heal 1 HP per hit (max {max}).",
	"呪われたアンプ": "Cursed Amp",
	"四つ葉のクローバー": "Four-Leaf Clover",
	"回復薬": "Healing Potion",
	"売り切れ": "Sold out",
	"守": "S",
	"守りの薬": "Guard Potion",
	"完了": "Done",
	"宝": "T",
	"宝箱": "Treasure",
	"実績 %d / %d": "Achievements %d / %d",
	"実績解除！": "Achievement Unlocked!",
	"山札 %d": "Draw %d",
	"幸運のコイン": "Lucky Coin",
	"店": "$",
	"店を出る": "Leave shop",
	"強": "E",
	"強化するカードを選ぶ": "Choose a card to upgrade",
	"弾{n}発 各{dmg}": "{n} bolts: {dmg} each",
	"心が安らぎ、HPが15回復した。": "You feel at peace. Healed 15 HP.",
	"怪しい宝箱": "Suspicious Chest",
	"戦": "B",
	"戦闘ごとに最初の被弾を無効化。": "Block the first hit of each battle.",
	"戦闘開始時にエコー待機状態になる。": "Start each battle with Echo ready.",
	"戦闘開始時にシールド10。": "Start each battle with 10 shield.",
	"戦闘開始時にシールド8。シールド獲得量+25%。": "Start each battle with 8 shield. +25% shield gained.",
	"扇形{dmg}+スタン": "Cone {dmg} + stun",
	"投げ銭を奪い取った。30G獲得、HPが8減った。": "You grabbed the tips. +30G, lost 8 HP.",
	"押すのが遅れる/早いと感じたら調整。ずれが大きい時はキャリブレーションが便利です。": "Adjust if presses feel late/early. Calibration helps when it's way off.",
	"挑戦者": "Challenger",
	"捨て札 %d": "Discard %d",
	"接触した敵に{n}": "{n} to touching enemies",
	"撃破数: %d    戦闘数: %d": "Kills: %d    Battles: %d",
	"敵HP+25% / 獲得ゴールド+50%": "Enemy HP +25% / Gold gain +50%",
	"敵が密集する場所に2拍後に着弾。{dmg}ダメージ。": "Lands on the densest enemy cluster in 2 beats. {dmg} damage.",
	"敵のHP+10%。": "Enemy HP +10%.",
	"敵を減速 {beats}拍": "Slow enemies, {beats} beats",
	"早い": "Early",
	"最大6体を貫く弾。{dmg}ダメージ。": "A bolt piercing up to 6 enemies. {dmg} damage.",
	"最大HP+15(取得時に全回復分も+15)。": "Max HP +15 (also heals 15 on pickup).",
	"最大HP-10を捧げる: レリックを得る": "Sacrifice 10 max HP: gain a relic",
	"最大HPの30%を回復。": "Heal 30% of max HP.",
	"最大エネルギー+1 / 最大HP-15%": "Max energy +1 / Max HP -15%",
	"最大エネルギー+1。": "Max energy +1.",
	"最高 %dウェーブ": "Best: wave %d",
	"最高コンボ: %d": "Best combo: %d",
	"最高到達階: %d": "Best floor: %d",
	"次に使うカードを2回発動する。": "Your next card triggers twice.",
	"次の{n}枚 威力1.5倍": "Next {n} cards x1.5",
	"次の{n}枚のカードの威力が1.5倍。": "Your next {n} cards are 1.5x as powerful.",
	"次のカード": "Next card",
	"次のカードを2回発動": "Next card triggers twice",
	"氷": "I",
	"氷結薬": "Freeze Potion",
	"活力薬": "Energy Potion",
	"減速 %d": "Slow %d",
	"満杯": "Full",
	"焚き火のそばで、ひと息つく。": "You catch your breath by the campfire.",
	"焚き火の薪": "Campfire Wood",
	"無傷のボス戦": "Flawless Boss",
	"無視する": "Ignore it",
	"爆": "B",
	"爆弾": "Bomb",
	"狂": "F",
	"狂乱薬": "Fury Potion",
	"獲得ゴールド+50%。": "+50% gold gained.",
	"王": "K",
	"画面をドラッグで移動": "Drag to move",
	"画面を横向きにしてください": "Please rotate to landscape",
	"画面揺れ": "Screen shake",
	"疾風": "Gale",
	"癒": "H",
	"直前に使ったカードをもう一度発動。": "Trigger the last card you played again.",
	"直前のカードを再発動": "Repeat the last card",
	"瞬間移動+無敵1秒": "Blink + 1s invulnerable",
	"祭壇が応えた。レリック「%s」を得た。": "The altar answered. Got relic \"%s\".",
	"祭壇は何も応えなかった。": "The altar did not answer.",
	"移動方向へ瞬間移動し、1秒間無敵。": "Blink in your move direction and be invulnerable for 1s.",
	"移動速度+15%。": "Move speed +15%.",
	"移動速度+15%。ビートごとの自動弾が2発になる。": "Move speed +15%. Auto-bolts fire twice each beat.",
	"立ち去る": "Leave",
	"範囲{dmg} 吸収最大{max}": "Area {dmg}, drain up to {max}",
	"範囲{dmg}+吹き飛ばし": "Area {dmg} + knockback",
	"累計1000体を倒す。": "Defeat 1000 enemies in total.",
	"累計撃破: %d": "Total kills: %d",
	"終了": "Quit",
	"結果: %+d ms を設定しました": "Result: set to %+d ms",
	"続けて当てるとコンボ！ コンボ5を目指そう。": "Keep landing hits to build a combo! Aim for 5.",
	"外すとコンボは0に戻る。ダメージもUPするよ。": "Missing resets it to 0. Combos boost your damage.",
	"罠だった！ HPが15減った。": "A trap! Lost 15 HP.",
	"聴く: HPを15回復": "Listen: heal 15 HP",
	"自動キャリブレーション": "Auto-calibrate",
	"自動弾+{n} (永続)": "Auto-bolt +{n} (permanent)",
	"自動弾が2体を貫通する。": "Auto-bolts pierce 2 enemies.",
	"自動弾のダメージ+3。": "Auto-bolt damage +3.",
	"薬剤師": "Pharmacist",
	"解放済みアセンション: %d": "Ascension unlocked: %d",
	"触れる: カード1枚を強化 / HP-10": "Touch it: upgrade a card / lose 10 HP",
	"記録・実績": "Records & Achievements",
	"設定": "Settings",
	"貫通ビーム{dmg}": "Piercing beam {dmg}",
	"貫通弾": "Pierce Shot",
	"貫通弾 {dmg} (6体)": "Piercing bolt {dmg} (6 enemies)",
	"路上でリュートを弾く吟遊詩人が、こちらをじっと見ている。": "A bard playing the lute on the road is staring at you.",
	"近い敵{n}体に雷撃。各{dmg}ダメージ。": "Lightning strikes the {n} nearest enemies. {dmg} damage each.",
	"近くの敵に弾を{n}発。各{dmg}ダメージ。": "Fire {n} bolts at nearby enemies. {dmg} damage each.",
	"通常の難易度。": "Standard difficulty.",
	"進む": "Continue",
	"進む [S]": "Continue [S]",
	"進む場所を選べ": "Choose where to go",
	"遅い": "Late",
	"重低音を響かせる古い祭壇。捧げ物を求めているようだ。": "An old altar throbbing with deep bass. It seems to want an offering.",
	"金色の PERFECT を2回出そう！": "Land PERFECT (gold) twice!",
	"丸が輪に重なった瞬間に押す(判定は±0.07秒)。": "Press the instant a dot lands on the ring (window: ±0.07s).",
	"金貨が詰まっていた！ 70G獲得。": "Full of gold coins! +70G.",
	"鉄の心臓": "Iron Heart",
	"鉄の鼓動": "Iron Pulse",
	"鋭い剣": "Sharp Sword",
	"鍛える  カード強化": "Forge  Upgrade a card",
	"鍵のかかっていない宝箱。罠かもしれない。": "An unlocked chest. It might be a trap.",
	"閉じる": "Close",
	"開ける: 50%で70G / 50%でHP-15": "Open: 50% +70G / 50% lose 15 HP",
	"音楽音量": "Music volume",
	"＋": "+",
	"－": "-",
	"？": "?",
	"？？？": "???",
	"第%d幕  %d / %d階": "Act %d  Floor %d / %d",
	"到達: 第%d幕  %d / %d階": "Reached: Act %d  Floor %d / %d",
	"第%d幕  開幕": "ACT %d",
	"長さ: 2幕(フル)": "Length: 2 acts (full)",
	"長さ: 1幕(ショート)": "Length: 1 act (short)",
	"第2幕へ": "Into Act 2",
	"第2幕に到達する。": "Reach Act 2.",
	"真のクリア": "True Clear",
	"最終ボス「マエストロ」を倒す。": "Defeat the final boss, the Maestro.",
	"マエストロ": "Maestro",
	"ステージ攻略で第1幕のボスを倒すと解放": "Unlock by defeating the Act 1 boss in Climb mode",
	"2つの幕(各10階+ボス)を勝ち抜き、最後のボスを倒せ。\nバトル・エリート・休憩・ショップ・イベント・宝箱。\n難易度(アセンション)で何度も挑める。": "Fight through two acts (10 floors + boss each) and defeat the final boss.\nBattles, elites, rests, shops, events, treasure.\nReplay at higher Ascension levels.",
	"ビートに合わせて準備！": "Get ready to the beat!",
	"ハンドクラップ": "Handclap",
	"リムショット": "Rimshot",
	"ウッドブロック": "Woodblock",
	"フィンガースナップ": "Finger snap",
	"音声・リズム": "Audio & Rhythm",
	"ゲーム": "Game",
	"毎拍に鳴らす": "Every beat",
	"2・4拍のみ鳴らす": "Beats 2 & 4 only",
	"クラップ音量": "Clap volume",
	"クラップの音": "Clap sound",
	"戦闘BGM": "Battle BGM",
	"クラップは戦闘・チュートリアル・この画面で拍を知らせます。戦闘開始時は4拍のカウントダウン付き。": "Claps mark the beat in battle, the tutorial and this screen. Battles start with a 4-beat countdown.",
	"▼ 選択中 ▼": "▼ SELECTED ▼",
	"キャラを決めたら出発！(Enter)": "Pick a character, then GO! (Enter)",
	"← → / A D で選択   Enter / Space で決定   1〜4 で直接選択": "←/→ or A/D to choose   Enter/Space to confirm   1-4 to pick directly",
	"+%d G 獲得": "+%d G",
	"獲得！": "Taken!",
	"スキップして進む [S]": "Skip & continue [S]",
	"強化の確認 - 性能比較": "Confirm Upgrade - Before / After",
	"現在": "Current",
	"強化後": "Upgraded",
	"強化する [Enter]": "Upgrade [Enter]",
	"もどる [Esc]": "Back [Esc]",
	"コスト": "Cost",
	"ダメージ": "Damage",
	"効果量": "Amount",
	"持続拍数": "Beats",
	"係数": "Factor",
	"上限": "Max",
	"変化: 名前に + が付く": "Changes: gets a + upgrade",
	"★ デイリー: %s": "★ Daily: %s",
	"★ 本日のルール ★": "★ Today's rule ★",
	"今日だけの固定マップ・キャラ・特殊ルール。\n\n★ 本日のルール ★\n": "Fixed map, character and a special rule, today only.\n\n★ Today's rule ★\n",
	"CC0素材: Kenney  /  音楽・効果音は自作": "CC0 assets: Kenney  /  Music & claps: original",
	"キー設定": "Key Bindings",
	"カード%d": "Card %d",
	"ポーション%d": "Potion %d",
	"上へ移動": "Move up",
	"下へ移動": "Move down",
	"左へ移動": "Move left",
	"右へ移動": "Move right",
	"キーを押す…": "Press a key...",
	"キー1": "Key 1",
	"キー2": "Key 2",
	"ボタンを押してから割り当てたいキーを押します(Escでキャンセル)。同じキーは他の操作から外れます。": "Click a button, then press the key to assign (Esc cancels). A key already in use is taken from the other action.",
	"初期設定に戻す": "Reset to defaults",
	"ビートを試す": "Test the beat",
	"Space / クリック": "Space / Click",
	"右の円をクリック/Spaceで押すと、判定とズレ(ms)を確認できます。": "Click the circle (or press Space) to see your judgement and offset in ms.",
	"平均 %+d ms  (%d回)": "Average %+d ms  (%d taps)",
	"平均をオフセットに反映": "Apply average to offset",
	"メニュー": "Menu",
	"Esc で閉じる": "Esc to close",
	"タイトルへ戻る": "Back to title",
	"タイトルに戻りますか？": "Return to the title?",
	"進行中のランは失われます。": "Your current run will be lost.",
	"はい": "Yes",
	"いいえ": "No",
	"獲得！(もう一度押すと取消)": "Taken! (press again to undo)",
	"+%d G 獲得  /  別のカードを押すと変更できます": "+%d G  /  Press another card to switch",
	"キャラを決めたら出発！(Enter)   ←→キャラ  ↑↓アセンション  Lで長さ切替": "Pick a character, then GO! (Enter)   ←→ character  ↑↓ ascension  L length",
	# --- additions (new UI strings) ---
	"言語 / Language": "Language / 言語",
	"日本語": "日本語",
	"フラッシュ軽減": "Reduce flashes",
	"判定アシスト": "Timing assist",
	"オフ": "Off",
	"広い": "Wide",
	"とても広い": "Very wide",
	"早い・遅い": "Early / Late",
}
